/* DO NOT EDIT THIS FILE! */

const { Order, Customer } = require('./db');
const Furniture = require('../furniture-db/db').Furniture;

const customers = [
    {
        name: 'Elon Musk',
        email: 'elon@spacex.com'
    },
    {
        name: 'Warren Buffet',
        email: 'warren@one.com'
    },
    {
        name: 'Larry Ellison',
        email: 'larry@oracle.com'
    },
    {
        name: 'Michael Bloomberg',
        email: 'mike@bloomberg.com'
    },
    {
        name: 'Melinda Gates',
        email: 'melinda@microsoft.com'
    }
];

const furnitureIds = [
    '5be83623fb6fc06239e0f14e',
    '5be836bdfb6fc06239e0f174',
    '5be836e5fb6fc06239e0f183',
    '5be83740fb6fc06239e0f1a7',
    '5be8380afb6fc06239e0f1dc'
];

const getRandomFurnitureIds = () => {
    const randomStartIndex = Math.ceil(Math.random() * furnitureIds.length) - 1;
    const randomNumberOfItems = Math.ceil(Math.random() * (furnitureIds.length - randomStartIndex));

    return furnitureIds.slice(randomStartIndex, randomNumberOfItems + randomStartIndex);
}

const asyncLoop = async (collection, cb) => {
    for (let i = 0; i < collection.length; i++) {
        await cb(collection[i], i, collection);
    }
};

const seed = async () => {
    const areCustomersEmpty = await Customer.countDocuments() === 0;

    if (areCustomersEmpty) {
        console.log('Seeding customers...');
        await Customer.insertMany(customers);
    }

    const customerIds = (await Customer.find({})).map(c => c.id).slice(0, 4); // Get first four ids

    const areOrdersEmpty = await Order.countDocuments() === 0;

    if (areOrdersEmpty) {
        console.log('Seeding orders...');
        await asyncLoop(customerIds, async value => {
            const furnitureIds = getRandomFurnitureIds();
            const furnitures = await Furniture.find({ _id: { $in: furnitureIds } });
            const amount = furnitures.reduce((acc, currVal) => acc + currVal.price, 0);

            await Order.create({
                customerId: value,
                furnitureIds,
                amount
            });
        });
    }
}

(async () => {
    await seed();
    console.log('Done seeding...');
    process.exit(0);
})();
